name: 04 Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # 0. checkout code from the repo
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls ..
      - name: Setup Node
        uses: actions/setup-node
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm ci
        # working-directory: 04-using-actions
#       steps:
#       - name: Using the Checkout Action
#         uses: actions/checkout@v4
#   print-folders:
#     runs-on: ubuntu-latest
#     steps:
#         - name: Print the folders
#           run: echo ls

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: 04-using-actions/react-app
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4
#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20.x'
#       - name: Install Dependencies
#         run: npm ci
#       - name: Run Unit Tests
#         run: npm run test
