name: 05 - 1 - Event Filters and Activity Types

on:
  pull_request:
    types: [opened, synchronize]
    # Sequence of patterns matched against refs/heads
    branches: main

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Running whenever a PR is opened or synchronized AND base branch is main"
