name: 11 Working With Inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: "Skip deployment and only print build output"
        required: false
        default: false
      target:
        type: environment
        description: "Which environment will the deployment target"
      tag:
        type: choice
        description: "Release from which to build and deploy"
        options: [v1, v2, v3]
        default: v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building from tag ${{ inputs.tag }}"
  deploy:
    if: ${{ !inputs.dry-run }}
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.target }}
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ inputs.target.uppercase }}"
